### ISSUE TITLE
Various feature requests

### ISSUE THREAD

**Issue by dylmye** [GreenTurtwig/Material-Notepad#1]
Hi! I really love this notepad. It looks great.
I'm using the latest version on Windows 10 x64, and it would be nice to have some padding around the main body text so the text around the edge is a bit more readable.

I also have some other small issues if you'd like to hear them? :p

**Comment by GreenTurtwig** [comment]
Sure I'd love to hear some other issues, I'll add the padding soon. :-)  
Honestly I never expected anybody to use this, it was just a fun little thing I made. Glad you like it. :heart:

**Comment by dylmye** [comment]
Should I post them as seperate issues?
It's quite pretty. I've been looking to make my OS more "material"-y.

**Comment by GreenTurtwig** [comment]
Putting them here is fine. :-)  
Yeah, I like the material look, have material icons e.t.c on Ubuntu.

**Comment by dylmye** [comment]
Ok, here is what I was having problems with. :)

- Using context menu -> "Open With..." -> "Material Notepad" just opens the program rather than opening the file in MN. Possibly a command is needed? Like `"C:\Path\To\Notepad\MaterialNotepad.exe" "%s"` to open files? I'm not sure how Open With works.

- Aforementioned padding issue

- Help dialog could show the current version.

- The option to use other fonts, such as Roboto Mono, would be awesome. I think Windows at least allows you to access any font installed on the system.

- Also (or if the previous issue is too complex) allowing the user to change the font size. :)

- The title of the program in Windows shows as "Electron".

These are just small things and I don't know feasible it would be to implement these but it would be awesome. :100:

**Comment by GreenTurtwig** [comment]
I'll definatley take a look when I have time. Thanks. :-) :heart:

**Comment by dylmye** [comment]
Thanks, you're awesome. :)

**Comment by GreenTurtwig** [comment]
Sorry about the wait, I was pretty busy. But I've started working on things now. :-)

**Comment by GreenTurtwig** [comment]
Loading `txt`s by drag drop is done. :cat:

**Comment by dylmye** [comment]
Woo :D Thanks

**Comment by GreenTurtwig** [comment]
Working on the font size at the moment, works but I've just got to make it save. ;-)  
Here's also some things I've added in the meantime:  
![puush-linux 2016-10-04 at 03 09 04](https://cloud.githubusercontent.com/assets/15905797/19077474/aed782c2-8a44-11e6-9962-919c2445b627.png)
![puush-linux 2016-10-04 at 03 10 05](https://cloud.githubusercontent.com/assets/15905797/19077478/b5cf788c-8a44-11e6-98e9-6c613acdcb0d.png)

**Comment by dylmye** [comment]
That's awesome, love how the icons are greyed out. The padding on the text too :open_mouth:

**Comment by GreenTurtwig** [comment]
https://github.com/GreenTurtwig/Material-Notepad/releases/tag/1.2.0  
  
Let me know if anything is wrong, and I'll try and fix it straight away. I couldn't find an easy way to load fonts easily, so I just decided to add a checkbox in the "Font" dialog to switch between mono and normal. I still haven't figured out how to allow files to be opened directly with Material Notepad (open with), but that will hopefully be in the next version, and saving the windows size. :smile_cat:

**Comment by dylmye** [comment]
Damn, looks great! I'm going to close this issue and open another one for smaller stuff, because it looks better. ;)
